language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
install:
    - sudo python setup.py install
    - if [[ $TRAVIS_PYTHON_VERSION < 3.0 ]]; then pip install --use-mirrors pygtk; fi
    - pip install --use-mirrors pygobject
script: python setup.py build
notifications:
    email: false